---
name: Action

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-15-intel
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action
        uses: ./

      - name: Run butler
        run: butler -V
