---
name: Continuous Integration

"on":
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  targets:
    name: Enumerate Just recipes
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.export-targets.outputs.targets }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Export targets
        id: export-targets
        run: echo "targets=$(just --list | awk '/build-|check-|format-|lint-|test-/{print $1}' | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  checks:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    needs: targets

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.targets.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Flox
        uses: flox/install-flox-action@1128abd73431089ab9d871c893b4e72a729354e1 # v2.6.0

      - name: Remove Flox installer (if it exists)
        run: rm -f flox.x86_64-linux.deb

      - name: Run check with Just
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: just ${{ matrix.target }}

  success:
    name: All checks succeeded
    runs-on: ubuntu-latest

    permissions: {}

    needs: checks
    if: always()

    steps:
      - name: Check if all checks succeeded
        # `needs` is a list of job names, which themselves are generated from
        # the output of `just --list`, so we ignore the template injection here.
        # zizmor: ignore[template-injection]
        run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
