---
name: Action

"on":
  push:

jobs:
  # The repository contains the action itself in the dist/ directory. Whenever
  # code is pushed to the repository, we need to make sure that the action has
  # been rebuilt and is up-to-date.
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run package

      - name: Compare committed action with build result
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See diff below:"
            git diff
            exit 1
          fi
