---
name: setup-butler

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      matrix:
        os:
          - macos-15-intel
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run action
        uses: ./

      - name: Run butler
        run: butler -V
