---
name: TypeScript

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v40
        with:
          files: |
            package.json
            package-lock.json
            **/*.ts

      - name: Print changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: ./node_modules/.bin/eslint "**/*.ts"

  style:
    name: Check style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: ./node_modules/.bin/prettier --check "**/*.ts"

  test:
    name: Run tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4.0.0
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
